
package DoAnQLSV.GUI;

import DoAnQLSV.BLL.LoginBLL;

import java.sql.*;
import javax.swing.*;
/**
 *
 * @author kshin
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    protected LoginBLL loginBLL;    
    public LoginGUI() {
        initComponents();
        LoginBLL.testConnect();
        loginBLL = new LoginBLL();
    }
    public static ResultSet rs = null;
    public static PreparedStatement pst = null;
    public static String MSSV;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        btnQuenMatKhau = new com.k33ptoo.components.KButton();
        btnDangNhap = new com.k33ptoo.components.KButton();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(500, 250));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(500, 270));
        kGradientPanel1.setRequestFocusEnabled(false);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQuenMatKhau.setText("Quên mật khẩu");
        btnQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuenMatKhau.setkBorderRadius(30);
        btnQuenMatKhau.setkEndColor(new java.awt.Color(0, 255, 255));
        btnQuenMatKhau.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnQuenMatKhau.setkStartColor(new java.awt.Color(252, 203, 252));
        btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMatKhauActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 150, 40));

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnDangNhap.setkBorderRadius(30);
        btnDangNhap.setkEndColor(new java.awt.Color(0, 204, 255));
        btnDangNhap.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDangNhap.setkHoverStartColor(new java.awt.Color(204, 0, 204));
        btnDangNhap.setkStartColor(new java.awt.Color(252, 203, 252));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 160, 40));

        header.setOpaque(false);
        header.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG NHẬP");
        header.add(jLabel1);

        kGradientPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, 50));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 20, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tên đăng nhập");
        jPanel1.add(jLabel3);

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setToolTipText("");
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUsername.setCaretColor(new java.awt.Color(204, 0, 205));
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtUsername.setName(""); // NOI18N
        txtUsername.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mật khẩu");
        jPanel1.add(jLabel2);

        txtpassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtpassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpassword.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtpassword.setName(""); // NOI18N
        jPanel1.add(txtpassword);

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 400, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
            if(this.txtUsername.getText().equals("")|this.txtpassword.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this,"Chua nhap tai khoan va mat khau");
            }
            else 
            {

                if(LoginBLL.quyen!="Admin")
                    {                        
                    rs = LoginBLL.cLog(this.txtUsername.getText(), String.valueOf(this.txtpassword.getPassword()),"Admin");
                    try {
                        if(rs.next())
                        {
                                    JOptionPane.showMessageDialog(this,"Dang nhap Admin thanh cong");
                                    this.setVisible(false);
                                    new MenuGUI().setVisible(true);  
                        }else
                        {
                            JOptionPane.showMessageDialog(this,"Sai tên đăng nhập hoặc mật khẩu");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,e,"Thong bao",1);
                    }
                    }
                else
                    {
                    rs = LoginBLL.cLog(this.txtUsername.getText(), String.valueOf(this.txtpassword.getPassword()),"SV");
                    try {
                        if(rs.next())
                        {
                                    JOptionPane.showMessageDialog(this,"Đăng nhập sinh viên "+txtUsername.getText()+" thành công");
                                    this.setVisible(false);
                                    new MenuGUI().setVisible(true);  
                        }else
                        {
                            JOptionPane.showMessageDialog(this,"Sai tên đăng nhập hoặc mật khẩu");
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,e,"Thong bao",1);
                    }
                    }
                System.out.println("quyen"+LoginBLL.quyen);
            }

    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed

    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed

    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void btnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMatKhauActionPerformed
        this.setVisible(false);
        new QuenMatKhauGUI().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_btnQuenMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnDangNhap;
    private com.k33ptoo.components.KButton btnQuenMatKhau;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
