/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DoAnQLSV.GUI;

import DoAnQLSV.BLL.LoginBLL;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author badao
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuGUI() {
        initComponents();
        if(LoginBLL.quyen=="SV")
            {
                lop.setVisible(false);
                khoa.setVisible(false);
                monhoc.setVisible(false);
                bxh.setVisible(false);
                timkiem.setVisible(false);
                dangki.setVisible(false);      
                this.XinChaoTxt.setText("Xin chào sinh viên :"+LoginBLL.ID);
            }
        else
            {
                this.XinChaoTxt.setText("Xin chào:"+LoginBLL.ID);
            }
    }
    public static ResultSet rs = null;
    public static PreparedStatement pst = null;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        XinChaoTxt = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        sinhvien = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lop = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        khoa = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        monhoc = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        bxh = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        diem = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        timkiem = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        dangki = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        thoat = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(500, 250));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(500, 270));
        kGradientPanel1.setRequestFocusEnabled(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        XinChaoTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        XinChaoTxt.setForeground(new java.awt.Color(204, 204, 204));
        XinChaoTxt.setText("Xin chao");
        kGradientPanel1.add(XinChaoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 310, -1));

        header.setOpaque(false);
        header.setLayout(new java.awt.GridLayout(1, 0));
        kGradientPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 850, 30));

        kGradientPanel2.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 0, 204));
        kGradientPanel2.setMinimumSize(new java.awt.Dimension(500, 250));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(500, 270));
        kGradientPanel2.setRequestFocusEnabled(false);
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        sinhvien.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        sinhvien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sinhvien.setOpaque(false);
        sinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinhvienMouseClicked(evt);
            }
        });
        sinhvien.setLayout(new java.awt.GridLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-student-100.png")); // NOI18N
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sinhvien.add(jLabel14);

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SINH VIÊN");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sinhvien.add(jLabel15);

        jPanel1.add(sinhvien);

        lop.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        lop.setOpaque(false);
        lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lopMouseClicked(evt);
            }
        });
        lop.setLayout(new java.awt.GridLayout(1, 0));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-class-100.png")); // NOI18N
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lop.add(jLabel16);

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("LỚP");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lop.add(jLabel17);

        jPanel1.add(lop);

        khoa.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        khoa.setOpaque(false);
        khoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khoaMouseClicked(evt);
            }
        });
        khoa.setLayout(new java.awt.GridLayout(1, 0));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-faculty-100.png")); // NOI18N
        jLabel18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        khoa.add(jLabel18);

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("KHOA");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        khoa.add(jLabel19);

        jPanel1.add(khoa);

        monhoc.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        monhoc.setOpaque(false);
        monhoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monhocMouseClicked(evt);
            }
        });
        monhoc.setLayout(new java.awt.GridLayout(1, 0));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-subjects-100.png")); // NOI18N
        jLabel22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        monhoc.add(jLabel22);

        jLabel23.setBackground(new java.awt.Color(102, 102, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("MÔN HỌC");
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        monhoc.add(jLabel23);

        jPanel1.add(monhoc);

        bxh.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        bxh.setOpaque(false);
        bxh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bxhMouseClicked(evt);
            }
        });
        bxh.setLayout(new java.awt.GridLayout(1, 0));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-rank-100.png")); // NOI18N
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bxh.add(jLabel20);

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("BẢNG XẾP HẠNG");
        jLabel21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bxh.add(jLabel21);

        jPanel1.add(bxh);

        diem.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        diem.setOpaque(false);
        diem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diemMouseClicked(evt);
            }
        });
        diem.setLayout(new java.awt.GridLayout(1, 0));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-point-100.png")); // NOI18N
        jLabel24.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        diem.add(jLabel24);

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("ĐIỂM");
        jLabel25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        diem.add(jLabel25);

        jPanel1.add(diem);

        timkiem.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        timkiem.setOpaque(false);
        timkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timkiemMouseClicked(evt);
            }
        });
        timkiem.setLayout(new java.awt.GridLayout(1, 0));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-search-100.png")); // NOI18N
        jLabel26.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        timkiem.add(jLabel26);

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("TÌM KIẾM");
        jLabel27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        timkiem.add(jLabel27);

        jPanel1.add(timkiem);

        dangki.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        dangki.setOpaque(false);
        dangki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangkiMouseClicked(evt);
            }
        });
        dangki.setLayout(new java.awt.GridLayout(1, 0));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-registration-100.png")); // NOI18N
        jLabel28.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dangki.add(jLabel28);

        jLabel29.setBackground(new java.awt.Color(102, 102, 102));
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("ĐĂNG KÍ");
        jLabel29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dangki.add(jLabel29);

        jPanel1.add(dangki);

        thoat.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));
        thoat.setOpaque(false);
        thoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thoatMouseClicked(evt);
            }
        });
        thoat.setLayout(new java.awt.GridLayout(1, 0));

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-exit-100.png")); // NOI18N
        jLabel30.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        thoat.add(jLabel30);

        jLabel31.setBackground(new java.awt.Color(102, 102, 102));
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("ĐĂNG XUẤT");
        jLabel31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thoat.add(jLabel31);

        jPanel1.add(thoat);

        kGradientPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lopMouseClicked
        this.setVisible(false);
        new QuanLyLopGUI().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_lopMouseClicked

    private void khoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoaMouseClicked
        this.setVisible(false);
        new QuanLyKhoaGUI().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_khoaMouseClicked

    private void monhocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monhocMouseClicked
        this.setVisible(false);
        new QuanLyMonHocGUI().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_monhocMouseClicked

    private void bxhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bxhMouseClicked
        this.setVisible(false);
        new BXHGUI().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bxhMouseClicked

    private void diemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diemMouseClicked
        this.setVisible(false);
        new QuanLyDiemGUI().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_diemMouseClicked

    private void timkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timkiemMouseClicked
        this.setVisible(false);
        new TimKiemGUI().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_timkiemMouseClicked

    private void dangkiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangkiMouseClicked
        this.setVisible(false);
        new DangKiGUI().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_dangkiMouseClicked

    private void thoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thoatMouseClicked
        this.setVisible(false);
        new LoginGUI().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_thoatMouseClicked

    private void sinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinhvienMouseClicked
        this.setVisible(false);
        new QuanLySinhVienGUI().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_sinhvienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel XinChaoTxt;
    private javax.swing.JPanel bxh;
    private javax.swing.JPanel dangki;
    private javax.swing.JPanel diem;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel khoa;
    private javax.swing.JPanel lop;
    private javax.swing.JPanel monhoc;
    private javax.swing.JPanel sinhvien;
    private javax.swing.JPanel thoat;
    private javax.swing.JPanel timkiem;
    // End of variables declaration//GEN-END:variables
}
