
package DoAnQLSV.GUI;

import DoAnQLSV.BLL.DiemBLL;
import DoAnQLSV.BLL.HocKiBLL;
import DoAnQLSV.BLL.LoginBLL;
import DoAnQLSV.BLL.SinhVienBLL;
import DoAnQLSV.DAO.*;
import DoAnQLSV.DTO.DiemDTO;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;




/**
 *
 * @author badao
 */
public class QuanLyDiemGUI extends javax.swing.JFrame {

    protected HocKiBLL hocKiBLL;    
    protected DiemBLL diemBLL;
    String button;        
    private DiemDAO diemDAO;
    
    public QuanLyDiemGUI() {
        initComponents();
        diemDAO = new DiemDAO();
        if(LoginBLL.quyen=="SV")
        {
            txtMSSV.setEnabled(false);
            txtDiemCuoiKi.setEnabled(false);
            txtDiemQuaTrinh.setEnabled(false);
            txtMaMon.setEnabled(false);
            cbbMaHocKi.setEnabled(false);
            
            btnThem.setVisible(false);
            btnXoa.setVisible(false);
            btnSua.setVisible(false);
            btnLuu.setVisible(false);
            btnHuy.setVisible(false);
          
            
            diemBLL = new DiemBLL();
            diemBLL.layDiemTheoMSSV();
            diemBLL.hienThiDiemTheoMa(jTable1);
        }
        else{
            diemBLL = new DiemBLL();
            diemBLL.laydanhsachDiem();
            diemBLL.hienThiDanhSachDiem(jTable1);
        }
        
        
        hocKiBLL = new HocKiBLL();
        hocKiBLL.layDanhSachHocKi();
        hocKiBLL.LoadCBBMaHocKi(cbbMaHocKi);
        
            SetButton(true);
            LockTxt(true);
    }
    public void LockTxt(boolean val)       // Khóa hết Textbox và ComboBox trước khi chọn nút chức năng
        {
            txtMSSV.setEnabled(!val);
            txtMaMon.setEnabled(!val);
            txtDiemQuaTrinh.setEnabled(!val);
            txtDiemCuoiKi.setEnabled(!val);
            cbbMaHocKi.setEnabled(!val);
        }
        public void SetButton(boolean val)
        {
            btnThem.setEnabled(val);
            btnXoa.setEnabled(val);
            btnSua.setEnabled(val);
            btnLuu.setEnabled(!val);
            btnHuy.setEnabled(!val);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaMon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDiemQuaTrinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDiemCuoiKi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbMaHocKi = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        footer = new javax.swing.JPanel();
        btnThem = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        btnSua = new com.k33ptoo.components.KButton();
        btnLuu = new com.k33ptoo.components.KButton();
        btnHuy = new com.k33ptoo.components.KButton();
        btnQuayVe = new com.k33ptoo.components.KButton();
        header = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnExcel = new com.k33ptoo.components.KButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý điểm");

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 150, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MSSV", "Mã môn học", "Điểm quá trình", "Điểm cuối kì", "Điểm tổng kết", "Điểm chữ", "Mã học kì"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 810, 240));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-list-50.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã môn học");
        jPanel1.add(jLabel1);

        txtMaMon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaMon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMaMon.setToolTipText("");
        txtMaMon.setBorder(null);
        txtMaMon.setCaretColor(new java.awt.Color(204, 0, 205));
        txtMaMon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMaMon.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtMaMon.setName(""); // NOI18N
        txtMaMon.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtMaMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMonActionPerformed(evt);
            }
        });
        jPanel1.add(txtMaMon);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Điểm quá trình");
        jPanel1.add(jLabel2);

        txtDiemQuaTrinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiemQuaTrinh.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiemQuaTrinh.setToolTipText("");
        txtDiemQuaTrinh.setBorder(null);
        txtDiemQuaTrinh.setCaretColor(new java.awt.Color(204, 0, 205));
        txtDiemQuaTrinh.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDiemQuaTrinh.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtDiemQuaTrinh.setName(""); // NOI18N
        txtDiemQuaTrinh.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtDiemQuaTrinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemQuaTrinhActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiemQuaTrinh);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Điểm cuối kì");
        jPanel1.add(jLabel3);

        txtDiemCuoiKi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiemCuoiKi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiemCuoiKi.setToolTipText("");
        txtDiemCuoiKi.setBorder(null);
        txtDiemCuoiKi.setCaretColor(new java.awt.Color(204, 0, 205));
        txtDiemCuoiKi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDiemCuoiKi.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtDiemCuoiKi.setName(""); // NOI18N
        txtDiemCuoiKi.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtDiemCuoiKi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemCuoiKiActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiemCuoiKi);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mã học kì");
        jPanel1.add(jLabel5);

        cbbMaHocKi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(cbbMaHocKi);

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 400, 180));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mã sinh viên");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(jLabel6);

        txtMSSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMSSV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtMSSV);

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 280, 40));

        footer.setOpaque(false);
        footer.setLayout(new java.awt.GridLayout(1, 6, 35, 0));

        btnThem.setText("Thêm");
        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setkBorderRadius(30);
        btnThem.setkEndColor(new java.awt.Color(0, 204, 255));
        btnThem.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnThem.setkHoverStartColor(new java.awt.Color(204, 0, 204));
        btnThem.setkStartColor(new java.awt.Color(252, 203, 252));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        footer.add(btnThem);

        btnXoa.setText("Xóa");
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setkBorderRadius(30);
        btnXoa.setkEndColor(new java.awt.Color(0, 255, 255));
        btnXoa.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnXoa.setkStartColor(new java.awt.Color(252, 203, 252));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        footer.add(btnXoa);

        btnSua.setText("Sửa");
        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setkBorderRadius(30);
        btnSua.setkEndColor(new java.awt.Color(0, 255, 255));
        btnSua.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSua.setkStartColor(new java.awt.Color(252, 203, 252));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        footer.add(btnSua);

        btnLuu.setText("Lưu");
        btnLuu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLuu.setkBorderRadius(30);
        btnLuu.setkEndColor(new java.awt.Color(0, 255, 255));
        btnLuu.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnLuu.setkStartColor(new java.awt.Color(252, 203, 252));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });
        footer.add(btnLuu);

        btnHuy.setText("Hủy");
        btnHuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHuy.setkBorderRadius(30);
        btnHuy.setkEndColor(new java.awt.Color(0, 255, 255));
        btnHuy.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnHuy.setkStartColor(new java.awt.Color(252, 203, 252));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        footer.add(btnHuy);

        btnQuayVe.setText("Quay về");
        btnQuayVe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuayVe.setkBorderRadius(30);
        btnQuayVe.setkEndColor(new java.awt.Color(0, 255, 255));
        btnQuayVe.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnQuayVe.setkStartColor(new java.awt.Color(252, 203, 252));
        btnQuayVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayVeActionPerformed(evt);
            }
        });
        footer.add(btnQuayVe);

        kGradientPanel1.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 780, 30));

        header.setOpaque(false);
        header.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("QUẢN LÝ ĐIỂM");
        header.add(jLabel7);

        kGradientPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, 30));

        btnExcel.setForeground(new java.awt.Color(0, 0, 0));
        btnExcel.setText("XUẤT FILE ĐIỂM");
        btnExcel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcel.setkBorderRadius(30);
        btnExcel.setkEndColor(new java.awt.Color(0, 204, 255));
        btnExcel.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnExcel.setkHoverStartColor(new java.awt.Color(204, 0, 204));
        btnExcel.setkStartColor(new java.awt.Color(252, 203, 252));
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiemCuoiKiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemCuoiKiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemCuoiKiActionPerformed

    private void txtDiemQuaTrinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemQuaTrinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemQuaTrinhActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        LockTxt(true);
        SetButton(true);            // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        LockTxt(true);
        if(button=="them"){
             if (this.txtMSSV.getText().length() == 0)
        {
              JOptionPane.showMessageDialog(null,"MSSV không được bỏ trống","Thông báo",1);
            txtMSSV.grabFocus();
            txtMSSV.setBackground(Color.red);
            return;
        }
        if(this.txtMSSV.getText().length()>10)
        {
              JOptionPane.showMessageDialog(null,"MSSV không được vượt quá 10 ký tự","Thông báo",1);
        txtMSSV.grabFocus();
        txtMSSV.setBackground(Color.red);
        return;
        }
        if (this.txtMaMon.getText().length() == 0)
        {
                   JOptionPane.showMessageDialog(null,"Mã môn học không được bỏ trống","Thông báo",1);
                  txtMaMon.grabFocus();
                  txtMaMon.setBackground(Color.red);
                  return;
        }
        if(this.txtMaMon.getText().length()>6)
        {
              JOptionPane.showMessageDialog(null,"Mã môn học không được vượt quá 6 ký tự","Thông báo",1);
        txtMaMon.grabFocus();
        txtMaMon.setBackground(Color.red);
        return;
        }
        if (this.txtDiemQuaTrinh.getText().length() == 0)
        {
             JOptionPane.showMessageDialog(null,"Điểm quá trình không được bỏ trống","Thông báo",1);
             txtDiemQuaTrinh.grabFocus();
             txtDiemQuaTrinh.setBackground(Color.red);
             return;
        }
        if (Float.parseFloat(txtDiemQuaTrinh.getText())>10||Float.parseFloat(txtDiemQuaTrinh.getText())<0)
        {
             JOptionPane.showMessageDialog(null,"Điểm quá trình không được > 10 hoặc < 0","Thông báo",1);
             txtDiemQuaTrinh.grabFocus();
             txtDiemQuaTrinh.setBackground(Color.red);
             return;
        }        
        if (this.txtDiemCuoiKi.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Điểm cuối kỳ không được bỏ trống","Thông báo",1);
             txtDiemCuoiKi.grabFocus();
             txtDiemCuoiKi.setBackground(Color.red);
             return;
        }
        if (Float.parseFloat(txtDiemCuoiKi.getText())>10||Float.parseFloat(txtDiemCuoiKi.getText())<0)
        {
            JOptionPane.showMessageDialog(null,"Điểm cuối kỳ không được > 10 hoặc < 0","Thông báo",1);
             txtDiemCuoiKi.grabFocus();
             txtDiemCuoiKi.setBackground(Color.red);
             return;
        }
        DiemDTO diem = new DiemDTO();
        diem.setMSSV(txtMSSV.getText());
        diem.setMaMon(txtMaMon.getText());
        diem.setDiemQuaTrinh(Float.parseFloat(txtDiemQuaTrinh.getText()));
        diem.setDiemThi(Float.parseFloat(txtDiemCuoiKi.getText()));
        diem.setMaHocKi((String) cbbMaHocKi.getSelectedItem());        
        diemBLL.themDiem(diem);
        diemBLL.laydanhsachDiem();
        diemBLL.hienThiDanhSachDiem(jTable1);
        JOptionPane.showMessageDialog(this, diemBLL.message, "Thêm điểm", JOptionPane.INFORMATION_MESSAGE);  
            }
        if(button=="sua"){
 if (this.txtMSSV.getText().length() == 0)
        {
              JOptionPane.showMessageDialog(null,"MSSV không được bỏ trống","Thông báo",1);
            txtMSSV.grabFocus();
            txtMSSV.setBackground(Color.red);
            return;
        }
        if(this.txtMSSV.getText().length()>10)
        {
              JOptionPane.showMessageDialog(null,"MSSV không được vượt quá 10 ký tự","Thông báo",1);
        txtMSSV.grabFocus();
        txtMSSV.setBackground(Color.red);
        return;
        }
        if (this.txtMaMon.getText().length() == 0)
        {
                   JOptionPane.showMessageDialog(null,"Mã môn học không được bỏ trống","Thông báo",1);
                  txtMaMon.grabFocus();
                  txtMaMon.setBackground(Color.red);
                  return;
        }
        if(this.txtMaMon.getText().length()>6)
        {
              JOptionPane.showMessageDialog(null,"Mã môn học không được vượt quá 6 ký tự","Thông báo",1);
        txtMaMon.grabFocus();
        txtMaMon.setBackground(Color.red);
        return;
        }
        if (this.txtDiemQuaTrinh.getText().length() == 0)
        {
             JOptionPane.showMessageDialog(null,"Điểm quá trình không được bỏ trống","Thông báo",1);
             txtDiemQuaTrinh.grabFocus();
             txtDiemQuaTrinh.setBackground(Color.red);
             return;
        }
        if (Float.parseFloat(txtDiemQuaTrinh.getText())>10||Float.parseFloat(txtDiemQuaTrinh.getText())<0)
        {
             JOptionPane.showMessageDialog(null,"Điểm quá trình không được > 10 hoặc < 0","Thông báo",1);
             txtDiemQuaTrinh.grabFocus();
             txtDiemQuaTrinh.setBackground(Color.red);
             return;
        }        
        if (this.txtDiemCuoiKi.getText().length() == 0)
        {
            JOptionPane.showMessageDialog(null,"Điểm cuối kỳ không được bỏ trống","Thông báo",1);
             txtDiemCuoiKi.grabFocus();
             txtDiemCuoiKi.setBackground(Color.red);
             return;
        }
        if (Float.parseFloat(txtDiemCuoiKi.getText())>10||Float.parseFloat(txtDiemCuoiKi.getText())<0)
        {
            JOptionPane.showMessageDialog(null,"Điểm cuối kỳ không được > 10 hoặc < 0","Thông báo",1);
             txtDiemCuoiKi.grabFocus();
             txtDiemCuoiKi.setBackground(Color.red);
             return;
        }
        DiemDTO diem = new DiemDTO();
        diem.setMSSV(txtMSSV.getText());
        diem.setMaMon(txtMaMon.getText());
        diem.setDiemQuaTrinh(Float.parseFloat(txtDiemQuaTrinh.getText()));
        diem.setDiemThi(Float.parseFloat(txtDiemCuoiKi.getText()));
        diem.setMaHocKi((String) cbbMaHocKi.getSelectedItem()); 
        diemBLL.suaDiem(diem);
        diemBLL.laydanhsachDiem();
        diemBLL.hienThiDanhSachDiem(jTable1);
        JOptionPane.showMessageDialog(this, diemBLL.message, "Sửa điểm", JOptionPane.INFORMATION_MESSAGE);        
        }
        if(button=="xoa"){
if (this.txtMSSV.getText().length() == 0)
        {
              JOptionPane.showMessageDialog(null,"MSSV không được bỏ trống","Thông báo",1);
            txtMSSV.grabFocus();
            txtMSSV.setBackground(Color.red);
        }
        else
            if(this.txtMSSV.getText().length()>10)
            {
                  JOptionPane.showMessageDialog(null,"MSSV không được vượt quá 10 ký tự","Thông báo",1);
            txtMSSV.grabFocus();
            txtMSSV.setBackground(Color.red);
            }
            else
            {
            DiemDTO diem = new DiemDTO();
            diem.setMSSV(txtMSSV.getText());
            diem.setMaMon(txtMaMon.getText());
            diemBLL.xoaDiem(diem);
            diemBLL.laydanhsachDiem();
            diemBLL.hienThiDanhSachDiem(jTable1);
            JOptionPane.showMessageDialog(this, diemBLL.message, "Xóa điểm", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        SetButton(true);          // TODO add your handling code here:
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        	    button ="sua";
            LockTxt(false);
            SetButton(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

            button ="xoa";
            LockTxt(false);
            SetButton(false); 
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtMaMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
            button ="them";
            LockTxt(false);
            SetButton(false);                         // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnQuayVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayVeActionPerformed
        this.setVisible(false);
        new MenuGUI().setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_btnQuayVeActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
        new MenuGUI().setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();
            this.txtMSSV.setText(jTable1.getModel().getValueAt(row, 0).toString());
            this.txtMaMon.setText(jTable1.getModel().getValueAt(row, 1).toString());
            this.txtDiemQuaTrinh.setText(jTable1.getModel().getValueAt(row, 2).toString());      
            this.txtDiemCuoiKi.setText(jTable1.getModel().getValueAt(row, 3).toString()); 
            this.cbbMaHocKi.setSelectedItem(jTable1.getModel().getValueAt(row, 6).toString());// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        ArrayList<DiemDTO> diemList = new ArrayList<DiemDTO>();
        diemList = diemDAO.layDanhSachDiem();
        try
        {
        XSSFWorkbook wordkbook = new XSSFWorkbook();
        XSSFSheet sheet=wordkbook.createSheet("danhsach");
        XSSFRow row =null;
        Cell cell=null;
        row=sheet.createRow(2);
        cell=row.createCell(0,CellType.STRING);
        cell.setCellValue("DANH SÁCH ĐIỂM");
        
        row=sheet.createRow(3);
        cell=row.createCell(0,CellType.STRING);
        cell.setCellValue("MSSV");
        
        cell=row.createCell(1,CellType.STRING);
        cell.setCellValue("Mã môn");
        
        cell=row.createCell(2,CellType.STRING);
        cell.setCellValue("Điểm quá trình");
        
        cell=row.createCell(3,CellType.STRING);
        cell.setCellValue("Điểm cuối kì");
        
        cell=row.createCell(4,CellType.STRING);
        cell.setCellValue("Điểm tổng kết");

        cell=row.createCell(5,CellType.STRING);
        cell.setCellValue("Điểm chữ");

        cell=row.createCell(6,CellType.STRING);
        cell.setCellValue("Mã học kì");        
        for(int i=0; i<diemList.size(); i++)
        {
            //Modelbook book =arr.get(i);
            row=sheet.createRow(6+i);
           
            cell=row.createCell(0,CellType.STRING);
            cell.setCellValue(diemList.get(i).getMSSV());
            
            cell=row.createCell(1,CellType.STRING);
            cell.setCellValue(diemList.get(i).getMaMon());
            
            
            cell=row.createCell(2,CellType.NUMERIC);
            cell.setCellValue(diemList.get(i).getDiemQuaTrinh());
            
            cell=row.createCell(3,CellType.NUMERIC);
            cell.setCellValue(diemList.get(i).getDiemThi());
            
            cell=row.createCell(4,CellType.NUMERIC);
            cell.setCellValue(diemList.get(i).getDiemTongKet());

            cell=row.createCell(5,CellType.STRING);
            cell.setCellValue(diemList.get(i).getDiemChu());

            cell=row.createCell(6,CellType.STRING);
            cell.setCellValue(diemList.get(i).getMaHocKi());            
                                  
        }
        
        File f = new File("D://danhsach.xlsx");
        try 
        {
            FileOutputStream fis = new FileOutputStream(f);
            wordkbook.write(fis);
            fis.close();
        }
        catch (FileNotFoundException ex) {
            ex.printStackTrace();
       
        }
        JOptionPane.showMessageDialog(this, "in thanh cong D:\\danhsach");
        
        }
        
        
        catch(Exception ex)
        {
            ex.printStackTrace();
              JOptionPane.showMessageDialog(this, "Loi mo file");
        }
         // TODO add your handling code here:
    }//GEN-LAST:event_btnExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyDiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyDiemGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnExcel;
    private com.k33ptoo.components.KButton btnHuy;
    private com.k33ptoo.components.KButton btnLuu;
    private com.k33ptoo.components.KButton btnQuayVe;
    private com.k33ptoo.components.KButton btnSua;
    private com.k33ptoo.components.KButton btnThem;
    private com.k33ptoo.components.KButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaHocKi;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtDiemCuoiKi;
    private javax.swing.JTextField txtDiemQuaTrinh;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtMaMon;
    // End of variables declaration//GEN-END:variables
}
