
package DoAnQLSV.GUI;

import DoAnQLSV.BLL.DangKiBLL;
import DoAnQLSV.BLL.LoginBLL;
import DoAnQLSV.DTO.DangKiDTO;
import DoAnQLSV.DTO.SinhVienDTO;
import DoAnQLSV.util.Validation;
import java.awt.Color;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author kshin
 */
public class QuenMatKhauGUI extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */   
    protected DangKiBLL dangKiBLL;    
    protected LoginBLL loginBLL;       

    public QuenMatKhauGUI() {
        initComponents();
        LoginBLL.testConnect();
        loginBLL = new LoginBLL();
        dangKiBLL = new DangKiBLL();
    }
    public static ResultSet rs = null;
    public static PreparedStatement pst = null;
    public static String MSSV;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        btnQuenMatKhau = new com.k33ptoo.components.KButton();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtConfirmPassword = new javax.swing.JPasswordField();
        btnDangNhap = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(500, 250));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(500, 270));
        kGradientPanel1.setRequestFocusEnabled(false);
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQuenMatKhau.setText("Quên mật khẩu");
        btnQuenMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnQuenMatKhau.setkBorderRadius(30);
        btnQuenMatKhau.setkEndColor(new java.awt.Color(0, 255, 255));
        btnQuenMatKhau.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnQuenMatKhau.setkStartColor(new java.awt.Color(252, 203, 252));
        btnQuenMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuenMatKhauActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 150, 40));

        header.setOpaque(false);
        header.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUÊN MẬT KHẨU");
        header.add(jLabel1);

        kGradientPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, 50));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(8, 1, 10, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tên đăng nhập");
        jPanel1.add(jLabel3);

        txtUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsername.setToolTipText("");
        txtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtUsername.setCaretColor(new java.awt.Color(204, 0, 205));
        txtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsername.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtUsername.setName(""); // NOI18N
        txtUsername.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gmail");
        jPanel1.add(jLabel2);

        txtGmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtGmail.setToolTipText("");
        txtGmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtGmail.setCaretColor(new java.awt.Color(204, 0, 205));
        txtGmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtGmail.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtGmail.setName(""); // NOI18N
        txtGmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtGmail);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mật khẩu mới");
        jPanel1.add(jLabel4);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPassword.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtPassword.setName(""); // NOI18N
        jPanel1.add(txtPassword);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Xác nhận mật khẩu mới");
        jPanel1.add(jLabel5);

        txtConfirmPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtConfirmPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConfirmPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtConfirmPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        txtConfirmPassword.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtConfirmPassword.setName(""); // NOI18N
        jPanel1.add(txtConfirmPassword);

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 400, 350));

        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDangNhap.setkBorderRadius(30);
        btnDangNhap.setkEndColor(new java.awt.Color(0, 255, 255));
        btnDangNhap.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDangNhap.setkStartColor(new java.awt.Color(252, 203, 252));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 150, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed

    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed

    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void btnQuenMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuenMatKhauActionPerformed
                if (this.txtUsername.getText().length() == 0)
                {
                    JOptionPane.showMessageDialog(null,"Tên tài khoản không được bỏ trống","Thông báo",1);
                    txtUsername.grabFocus();
                    txtUsername.setBackground(Color.red);
                    return;
                }
                if (this.txtUsername.getText().length() > 10)
                {
                    JOptionPane.showMessageDialog(null,"Tên tài khoản không được vượt quá 10 ký tự","Thông báo",1);
                    txtUsername.grabFocus();
                    txtUsername.setBackground(Color.red);
                    return;
                }
                if (this.txtPassword.getText().length() == 0)
                {
                    JOptionPane.showMessageDialog(null,"Mật khẩu không được bỏ trống","Thông báo",1);
                    txtPassword.grabFocus();
                    txtPassword.setBackground(Color.red);
                    return;
                }
                if (this.txtPassword.getText().length() > 50)
                {
                    JOptionPane.showMessageDialog(null,"Mật khẩu không được vượt quá 50 ký tự","Thông báo",1);
                    txtPassword.grabFocus();
                    txtPassword.setBackground(Color.red);
                    return;
                }        
                boolean flag;
                flag = Validation.isEmail(txtGmail.getText());
                if (flag == false)
                {
                    JOptionPane.showMessageDialog(null,"Email không đúng định dạng","Thông báo",1);
                    txtGmail.grabFocus();
                    txtGmail.setBackground(Color.red);
                    return;
                }
                if (this.txtConfirmPassword.getText().length() == 0)
                {
                    JOptionPane.showMessageDialog(null,"Mật khẩu xác nhận không được bỏ trống","Thông báo",1);
                    txtConfirmPassword.grabFocus();
                    txtConfirmPassword.setBackground(Color.red);
                    return;
                }
                if (this.txtConfirmPassword.getText().length() > 50)
                {
                    JOptionPane.showMessageDialog(null,"Mật khẩu xác nhận không được vượt quá 50 ký tự","Thông báo",1);
                    txtConfirmPassword.grabFocus();
                    txtConfirmPassword.setBackground(Color.red);
                    return;
                } 
                if (this.txtConfirmPassword.getText().compareTo(this.txtPassword.getText())!=0)
                {
                    JOptionPane.showMessageDialog(null,"Mật khẩu xác nhận không khớp mật khẩu","Thông báo",1);
                    txtConfirmPassword.grabFocus();
                    txtConfirmPassword.setBackground(Color.red);
                    return;
                }
            rs = LoginBLL.bLog(this.txtUsername.getText(), this.txtGmail.getText(),"SV");
            try {
                if(rs.next())
                {
                DangKiDTO taikhoan = new DangKiDTO();
                taikhoan.setID(txtUsername.getText());
                taikhoan.setMSSV(txtUsername.getText());
                taikhoan.setGmail(txtGmail.getText());
                taikhoan.setPassword(txtPassword.getText());
                taikhoan.setCofirm(txtConfirmPassword.getText());
                taikhoan.setQuyen("SV");        
                dangKiBLL.suaTaiKhoan(taikhoan);
                JOptionPane.showMessageDialog(this, dangKiBLL.message, "Sửa tài khoản", JOptionPane.INFORMATION_MESSAGE);
                }else
                {
                    JOptionPane.showMessageDialog(this,"Sai tên đăng nhập hoặc gmail");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e,"Thong bao",1);
            }
    }//GEN-LAST:event_btnQuenMatKhauActionPerformed

    private void txtGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGmailActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        this.setVisible(false);
        new LoginGUI().setVisible(true); 
    }//GEN-LAST:event_btnDangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhauGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhauGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnDangNhap;
    private com.k33ptoo.components.KButton btnQuenMatKhau;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
