/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DoAnQLSV.GUI;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import DoAnQLSV.DTO.*;
import DoAnQLSV.BLL.*;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author badao
 */
public class TimKiemGUI extends javax.swing.JFrame {

    protected SinhVienBLL svBLL;    
    protected LopBLL lopBLL;  
    protected KhoaBLL khoaBLL;
    
        public static String temp;
    public TimKiemGUI() {
        initComponents();
        
        svBLL = new SinhVienBLL();
        svBLL.laydanhsachSV();

                jTable1.setModel(new DefaultTableModel());
        
        lopBLL = new LopBLL();
        lopBLL.laydanhsachLop();
        lopBLL.LoadCBBMaLop(cbbMaLop);
        
        khoaBLL = new KhoaBLL();
        khoaBLL.laydanhsachKhoa();
        khoaBLL.LoadCBBMaKhoa(cbbMaKhoa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        txtTong = new javax.swing.JLabel();
        btnQuayVe = new com.k33ptoo.components.KButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbbMaKhoa = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbbMaLop = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnTimKiem = new com.k33ptoo.components.KButton();
        btnXoa = new com.k33ptoo.components.KButton();
        btnReset = new com.k33ptoo.components.KButton();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTong.setForeground(new java.awt.Color(204, 204, 204));
        kGradientPanel1.add(txtTong, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 190, 20));

        btnQuayVe.setText("Quay về");
        btnQuayVe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuayVe.setkBorderRadius(30);
        btnQuayVe.setkEndColor(new java.awt.Color(0, 255, 255));
        btnQuayVe.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnQuayVe.setkStartColor(new java.awt.Color(252, 203, 252));
        btnQuayVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayVeActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnQuayVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 120, 30));

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 150, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MSSV", "Họ", "Tên", "Ngày sinh", "Giới tính", "Lớp", "Khoa"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        kGradientPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 810, 230));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Study\\icons8-list-50.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(5, 2, 20, 20));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("MSSV");
        jPanel1.add(jLabel7);

        txtMSSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMSSV.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMSSV.setToolTipText("");
        txtMSSV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtMSSV.setCaretColor(new java.awt.Color(204, 0, 205));
        txtMSSV.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMSSV.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtMSSV.setName(""); // NOI18N
        txtMSSV.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtMSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMSSVActionPerformed(evt);
            }
        });
        jPanel1.add(txtMSSV);

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Họ");
        jPanel1.add(jLabel2);

        txtHo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHo.setToolTipText("");
        txtHo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtHo.setCaretColor(new java.awt.Color(204, 0, 205));
        txtHo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtHo.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtHo.setName(""); // NOI18N
        txtHo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoActionPerformed(evt);
            }
        });
        jPanel1.add(txtHo);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tên");
        jPanel1.add(jLabel4);

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTen.setToolTipText("");
        txtTen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTen.setCaretColor(new java.awt.Color(204, 0, 205));
        txtTen.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTen.setMargin(new java.awt.Insets(16, 6, 2, 6));
        txtTen.setName(""); // NOI18N
        txtTen.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });
        jPanel1.add(txtTen);

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Khoa");
        jPanel1.add(jLabel5);

        cbbMaKhoa.setToolTipText("");
        cbbMaKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaKhoaActionPerformed(evt);
            }
        });
        jPanel1.add(cbbMaKhoa);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Lớp");
        jPanel1.add(jLabel3);

        cbbMaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaLopActionPerformed(evt);
            }
        });
        jPanel1.add(cbbMaLop);

        kGradientPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 480, 220));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 40, 20));

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimKiem.setkBorderRadius(30);
        btnTimKiem.setkEndColor(new java.awt.Color(0, 204, 255));
        btnTimKiem.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnTimKiem.setkHoverStartColor(new java.awt.Color(204, 0, 204));
        btnTimKiem.setkStartColor(new java.awt.Color(252, 203, 252));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel2.add(btnTimKiem);

        btnXoa.setText("Xóa");
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setkBorderRadius(30);
        btnXoa.setkEndColor(new java.awt.Color(0, 255, 255));
        btnXoa.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnXoa.setkStartColor(new java.awt.Color(252, 203, 252));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa);

        btnReset.setText("Reset");
        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setkBorderRadius(30);
        btnReset.setkEndColor(new java.awt.Color(0, 255, 255));
        btnReset.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnReset.setkStartColor(new java.awt.Color(252, 203, 252));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset);

        kGradientPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 80, 160));

        header.setOpaque(false);
        header.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM SINH VIÊN");
        header.add(jLabel1);

        kGradientPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 830, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayVeActionPerformed
        this.setVisible(false);
        new MenuGUI().setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_btnQuayVeActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed

        SinhVienDTO sv = new SinhVienDTO();
        LopDTO lop = new LopDTO();
        KhoaDTO k = new KhoaDTO();
        sv.setMSSV(txtMSSV.getText());
        sv.setHo(txtHo.getText());
        sv.setTen(txtTen.getText());
        lop.setMaLop((String) cbbMaLop.getSelectedItem());
        k.setMaKhoa((String) cbbMaKhoa.getSelectedItem());
        svBLL.Timkiem1(sv, lop, k, jTable1);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtMSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMSSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMSSVActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (this.txtMSSV.getText().length() == 0)
        {
              JOptionPane.showMessageDialog(null,"MSSV không được bỏ trống","Thông báo",1);
            txtMSSV.grabFocus();
            txtMSSV.setBackground(Color.red);
        }
        else{
        SinhVienDTO sv = new SinhVienDTO();
        sv.setMSSV(txtMSSV.getText());
        svBLL.xoaSinhVien(sv);

        JOptionPane.showMessageDialog(this, svBLL.message, "Xóa SV", JOptionPane.INFORMATION_MESSAGE); 
        
        LopDTO lop = new LopDTO();
        KhoaDTO k = new KhoaDTO();
        sv.setMSSV(txtMSSV.getText());
        sv.setHo(txtHo.getText());
        sv.setTen(txtTen.getText());
        lop.setMaLop((String) cbbMaLop.getSelectedItem());
        k.setMaKhoa((String) cbbMaKhoa.getSelectedItem());
        svBLL.Timkiem1(sv, lop, k, jTable1);
        
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        jTable1.setModel(new DefaultTableModel());
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void cbbMaKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaKhoaActionPerformed

        temp = cbbMaKhoa.getSelectedItem().toString();  


    }//GEN-LAST:event_cbbMaKhoaActionPerformed

    private void cbbMaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMaLopActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setVisible(false);
        new MenuGUI().setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
            DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();
            this.txtMSSV.setText(jTable1.getModel().getValueAt(row, 0).toString());
            this.txtHo.setText(jTable1.getModel().getValueAt(row, 1).toString());
            this.txtTen.setText(jTable1.getModel().getValueAt(row, 2).toString());

            this.cbbMaLop.setSelectedItem(jTable1.getModel().getValueAt(row, 5).toString());
            this.cbbMaKhoa.setSelectedItem(jTable1.getModel().getValueAt(row, 6).toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimKiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimKiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimKiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimKiemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimKiemGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnQuayVe;
    private com.k33ptoo.components.KButton btnReset;
    private com.k33ptoo.components.KButton btnTimKiem;
    private com.k33ptoo.components.KButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaKhoa;
    private javax.swing.JComboBox<String> cbbMaLop;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtTen;
    private javax.swing.JLabel txtTong;
    // End of variables declaration//GEN-END:variables
}
